In [40]:
import numpy as np

In [41]:
import mxnet as mx

In [42]:
from mnist import MNIST
#you can find python-mnist source code on https://github.com/sorki/python-mnist

datahandler = MNIST('../mnist_data_loader') #change for data path
train_data = datahandler.load_training()

In [43]:
image_array = np.asarray(train_data[0])

In [44]:
label_list = []
for i in train_data[1]:
    l = [0]*10
    l[i] = 1
    label_list.append(l)

label_array = np.asarray(label_list)

In [91]:
label_array[0]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [96]:
train_iter = mx.io.NDArrayIter(
    
    data = image_array[:19999],
    label = label_array[:19999],
    batch_size = 1,

)

In [97]:
val_iter = mx.io.NDArrayIter(
    
    data = image_array[19999:20699],
    label = label_array[19999:20699],
    batch_size = 1,

)

In [98]:
data = mx.symbol.Variable('data')
fc1  = mx.symbol.FullyConnected(data = data, num_hidden=784)
act1 = mx.symbol.Activation(data = fc1, act_type="sigmoid")
fc2  = mx.symbol.FullyConnected(data = act1, num_hidden=10)
mlp  = mx.symbol.SoftmaxOutput(data = fc2, name = 'softmax')

In [ ]:
model = mx.model.FeedForward(
    
    symbol = mlp,
    num_epoch = 5,
    learning_rate = .1

)

model.fit(X = train_iter)

In [106]:
model.predict(X = np.asarray([image_array[1]]))

array([[  1.18918806e-05,   2.39849793e-08,   6.84234820e-08,
          7.02071024e-09,   9.99982119e-01,   1.74904289e-06,
          5.80433168e-09,   3.46519960e-06,   6.34538765e-07,
          2.70154281e-08]], dtype=float32)

In [59]:
model.predict(X = np.asarray([image_array[0]]))

array([[ 0.10913225,  0.11410896,  0.09094781,  0.09803623,  0.09686648,
         0.09715251,  0.098118  ,  0.09613701,  0.09474541,  0.10475542]], dtype=float32)

In [62]:
test_iter = mx.io.NDArrayIter(
    
    data = image_array[0],
    batch_size = 1
)

In [57]:
digits = [0]*10
for i in label_array:
    digits[i] += 1
digits = [i/60000 for i in digits]

In [58]:
print(digits)

[0.09871666666666666, 0.11236666666666667, 0.0993, 0.10218333333333333, 0.09736666666666667, 0.09035, 0.09863333333333334, 0.10441666666666667, 0.09751666666666667, 0.09915]
